name: Generate Weather Animation

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      run: python path/to/your_script.py

    - name: Commit and push images
      run: |
        git config --local user.name "Khalid Hossain"
        git config --local user.email "khalidhossainagplus@gmail.com"
        git add .
        git commit -m "Update weather animation"
        git push
